### PR TITLE
Feature/add aural service

### PR DESCRIPTION
**Pull request by varatep**
For this PR, I'm unable to attempt registering on my local raspberry pi from my development environment. I receive a `cors` issue. Is there a workaround for this, or is the only way to test via flashing on staging with the new anax ui?

### CODE REVIEW

**Comment by bmpotter** [comment]
Yes, the CORS issue has been fixed in the exchange in staging, but not promoted to prod yet (see https://github.com/open-horizon/anax-ui/issues/70), so please test on staging.

**Comment by varatep** [comment]
@bmpotter Here are images of the new service segment during registration.

image 1
image 2
image 3

**Comment by chrod** [comment]
@varatep 
Can you update the text to the following: 
- More introductory-focused
- Separate privacy warning

_And please ensure that the default setting for "Send Audio" toggle is off._ 

**Main text:**
Horizon Aural classifies sounds on your device using a microphone.  Audio clips are passed to onboard Neural Networks once per second, where they are recognized by binary classifiers as "speech", "music", "bird song", and other distinct classes. As Aural's Neural Network models are trained on additional crowdsourced data, your device will be regularly updated with new classes.

**Send audio data to Horizon servers:**
If toggled ON, your device will send a few audio sample clips per day to Horizon servers for randomized public annotation (labeling) and automated Neural Network model improvement. While we appreciate your contributions, please do not enable sending of audio unless you are confident that the device will never be within range of sounds that should remain private.

**Comment by varatep** [comment]
@dyec Yes sir
Send audio is already disabled by default for user's privacy.

**Comment by varatep** [comment]
@chrod The latest push looks like this:

image 1

**Pull request merged**
